// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsLVONtmE-uvv3l8z-n15RSV3I_P4c8FU',
    appId: '1:73393679466:web:0e970d9d1a76e4c004ae13',
    messagingSenderId: '73393679466',
    projectId: 'todoflutter-df6ea',
    authDomain: 'todoflutter-df6ea.firebaseapp.com',
    storageBucket: 'todoflutter-df6ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hkiDTm4-VF3AcRdbp71KE7fgDXF38_4',
    appId: '1:73393679466:android:c8689dda6d9f9ff304ae13',
    messagingSenderId: '73393679466',
    projectId: 'todoflutter-df6ea',
    storageBucket: 'todoflutter-df6ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvZRjI_RgTT3IgaBqXHX4SWhxTiL0zJmc',
    appId: '1:73393679466:ios:2d05132a1f9c451804ae13',
    messagingSenderId: '73393679466',
    projectId: 'todoflutter-df6ea',
    storageBucket: 'todoflutter-df6ea.firebasestorage.app',
    iosBundleId: 'com.example.todoFireAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvZRjI_RgTT3IgaBqXHX4SWhxTiL0zJmc',
    appId: '1:73393679466:ios:2d05132a1f9c451804ae13',
    messagingSenderId: '73393679466',
    projectId: 'todoflutter-df6ea',
    storageBucket: 'todoflutter-df6ea.firebasestorage.app',
    iosBundleId: 'com.example.todoFireAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsLVONtmE-uvv3l8z-n15RSV3I_P4c8FU',
    appId: '1:73393679466:web:43b8e8f0b4a5868004ae13',
    messagingSenderId: '73393679466',
    projectId: 'todoflutter-df6ea',
    authDomain: 'todoflutter-df6ea.firebaseapp.com',
    storageBucket: 'todoflutter-df6ea.firebasestorage.app',
  );
}
